EXPERIMENT:
  ID: many2many # Give your experiment a unique ID which is used in the log
  SEED: 2

DATA_CONFIG:
  DATASET_NAME: MovingMnist
  DATALOADER:
    NUM_WORKER: 2
    SHUFFLE: True

MODEL:
  PEEP: True
  N_PAST_STEPS: 5 # Number of input range images
  N_FUTURE_STEPS: 3 # Number of predicted future range images
  MASK_THRESHOLD: 0.5 # Threshold for valid point mask classification
  NORM: batch # batch, group, none, instance

TRAIN:
  LR: 0.0001
  LR_EPOCH: 1
  LR_DECAY: 0.33
  MAX_EPOCH: 100
  BATCH_SIZE: 16
  BATCH_ACC: 1
  N_GPUS: 1
  LOG_EVERY_N_STEPS: 10
  LOSS_WEIGHT_CHAMFER_DISTANCE: 0.0
  LOSS_WEIGHT_RANGE_VIEW: 1.0
  LOSS_WEIGHT_MASK: 1.0

